-- Warehouse v2 foundation: append-only source metadata, operational evidence,
-- SCD2 enforcement, and incremental-load keys. This migration is additive and
-- preserves every existing browser and RPC contract.

create extension if not exists btree_gist with schema extensions;

create schema if not exists ops;
revoke all on schema ops from public, anon, authenticated;
grant usage on schema ops to service_role;

create table if not exists ops.pipeline_batches (
  batch_id uuid primary key,
  run_id uuid references public.pipeline_runs(run_id),
  source_name text not null default 'all',
  mode text not null check (mode in ('initial', 'incremental', 'backfill', 'demo')),
  requested_from date,
  requested_to date,
  cutoff_at timestamptz,
  status text not null check (status in ('created', 'running', 'success', 'failed')),
  source_rows integer not null default 0,
  checksum text,
  created_at timestamptz not null default clock_timestamp(),
  finished_at timestamptz
);

create table if not exists ops.etl_watermarks (
  source_name text primary key check (source_name in ('premium', 'claim')),
  watermark_ts timestamptz not null,
  watermark_source_id text not null,
  last_successful_run_id uuid references public.pipeline_runs(run_id),
  updated_at timestamptz not null default clock_timestamp()
);

create table if not exists ops.pipeline_stage_runs (
  stage_run_id bigserial primary key,
  run_id uuid not null references public.pipeline_runs(run_id) on delete cascade,
  stage_order smallint not null,
  stage_name text not null,
  status text not null check (status in ('running', 'success', 'failed', 'skipped')),
  started_at timestamptz not null default clock_timestamp(),
  finished_at timestamptz,
  duration_ms integer,
  input_rows integer not null default 0,
  inserted_rows integer not null default 0,
  updated_rows integer not null default 0,
  unchanged_rows integer not null default 0,
  recalculated_rows integer not null default 0,
  rejected_rows integer not null default 0,
  error_code text,
  sanitized_error text,
  unique (run_id, stage_order)
);

create index if not exists pipeline_stage_runs_run_idx
  on ops.pipeline_stage_runs (run_id, stage_order);

create table if not exists ops.quarantine_records (
  quarantine_id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.pipeline_runs(run_id),
  batch_id uuid references ops.pipeline_batches(batch_id),
  source_name text not null check (source_name in ('premium', 'claim')),
  source_txn_id text not null,
  reason_code text not null,
  severity text not null check (severity in ('warning', 'critical')),
  payload jsonb not null default '{}'::jsonb,
  disposition text not null default 'pending'
    check (disposition in ('pending', 'replayed', 'discarded')),
  quarantined_at timestamptz not null default clock_timestamp(),
  resolved_at timestamptz,
  recovered_by_run_id uuid references public.pipeline_runs(run_id)
);

create index if not exists quarantine_records_run_idx
  on ops.quarantine_records (run_id, disposition);
create unique index if not exists quarantine_one_pending_source_idx
  on ops.quarantine_records (source_name, source_txn_id)
  where disposition = 'pending';

alter table ops.pipeline_batches enable row level security;
alter table ops.etl_watermarks enable row level security;
alter table ops.pipeline_stage_runs enable row level security;
alter table ops.quarantine_records enable row level security;
revoke all on all tables in schema ops from public, anon, authenticated;
revoke all on all sequences in schema ops from public, anon, authenticated;
grant all on all tables in schema ops to service_role;
grant all on all sequences in schema ops to service_role;
alter default privileges in schema ops revoke all on tables from public, anon, authenticated;
alter default privileges in schema ops revoke all on sequences from public, anon, authenticated;

-- Treat staging as a private append-only landing zone. Service-role and owner
-- execution are retained; browser roles receive no policy and no privilege.
alter table staging.raw_premium_txn enable row level security;
alter table staging.raw_claim_txn enable row level security;
revoke all on schema staging from public, anon, authenticated;
revoke all on all tables in schema staging from public, anon, authenticated;
revoke all on all sequences in schema staging from public, anon, authenticated;
grant usage on schema staging to service_role;
grant all on all tables in schema staging to service_role;
grant all on all sequences in schema staging to service_role;
alter default privileges in schema staging revoke all on tables from public, anon, authenticated;
alter default privileges in schema staging revoke all on sequences from public, anon, authenticated;

alter table staging.raw_premium_txn
  add column if not exists landing_id bigint generated by default as identity,
  add column if not exists source_txn_id text,
  add column if not exists source_updated_at timestamptz,
  add column if not exists source_effective_date date,
  add column if not exists batch_id uuid,
  add column if not exists ingested_at timestamptz default clock_timestamp();

alter table staging.raw_claim_txn
  add column if not exists landing_id bigint generated by default as identity,
  add column if not exists source_txn_id text,
  add column if not exists source_updated_at timestamptz,
  add column if not exists source_effective_date date,
  add column if not exists batch_id uuid,
  add column if not exists ingested_at timestamptz default clock_timestamp();

insert into ops.pipeline_batches (
  batch_id, source_name, mode, status, source_rows, created_at, finished_at
) values (
  '00000000-0000-0000-0000-000000000001', 'all', 'initial', 'success',
  (select count(*) from staging.raw_premium_txn) +
  (select count(*) from staging.raw_claim_txn),
  clock_timestamp(), clock_timestamp()
) on conflict (batch_id) do nothing;

update staging.raw_premium_txn
set source_txn_id = coalesce(
      source_txn_id,
      'premium:' || md5(concat_ws('|', policy_number, txn_code, txn_date::text,
        effective_date::text, written_premium::text))
    ),
    source_updated_at = coalesce(
      source_updated_at,
      (coalesce(txn_date, effective_date, current_date)::timestamp at time zone 'UTC')
    ),
    source_effective_date = coalesce(source_effective_date, txn_date, effective_date),
    batch_id = coalesce(batch_id, '00000000-0000-0000-0000-000000000001'),
    ingested_at = coalesce(ingested_at, clock_timestamp());

update staging.raw_claim_txn
set source_txn_id = coalesce(
      source_txn_id,
      'claim:' || md5(concat_ws('|', claim_number, policy_number, txn_code,
        txn_date::text, effective_date::text, paid_loss::text, case_reserve::text))
    ),
    source_updated_at = coalesce(
      source_updated_at,
      (coalesce(txn_date, effective_date, current_date)::timestamp at time zone 'UTC')
    ),
    source_effective_date = coalesce(source_effective_date, txn_date, effective_date),
    batch_id = coalesce(batch_id, '00000000-0000-0000-0000-000000000001'),
    ingested_at = coalesce(ingested_at, clock_timestamp());

do $$
begin
  if exists (
    select 1 from staging.raw_premium_txn
    where landing_id is null or source_txn_id is null or source_updated_at is null
       or source_effective_date is null or batch_id is null or ingested_at is null
  ) or exists (
    select 1 from staging.raw_claim_txn
    where landing_id is null or source_txn_id is null or source_updated_at is null
       or source_effective_date is null or batch_id is null or ingested_at is null
  ) then
    raise exception 'Warehouse v2 source-metadata backfill produced null values';
  end if;
end
$$;

alter table staging.raw_premium_txn
  alter column source_txn_id set not null,
  alter column source_updated_at set not null,
  alter column source_effective_date set not null,
  alter column batch_id set not null,
  alter column ingested_at set not null;

alter table staging.raw_claim_txn
  alter column source_txn_id set not null,
  alter column source_updated_at set not null,
  alter column source_effective_date set not null,
  alter column batch_id set not null,
  alter column ingested_at set not null;

create unique index if not exists raw_premium_landing_id_uidx
  on staging.raw_premium_txn (landing_id);
create unique index if not exists raw_claim_landing_id_uidx
  on staging.raw_claim_txn (landing_id);
create index if not exists raw_premium_watermark_idx
  on staging.raw_premium_txn (source_updated_at, source_txn_id);
create index if not exists raw_claim_watermark_idx
  on staging.raw_claim_txn (source_updated_at, source_txn_id);
create index if not exists raw_premium_source_latest_idx
  on staging.raw_premium_txn (source_txn_id, source_updated_at desc, landing_id desc);
create index if not exists raw_claim_source_latest_idx
  on staging.raw_claim_txn (source_txn_id, source_updated_at desc, landing_id desc);
create index if not exists raw_premium_batch_idx on staging.raw_premium_txn (batch_id);
create index if not exists raw_claim_batch_idx on staging.raw_claim_txn (batch_id);

alter table public.fact_premium
  add column if not exists source_txn_id text,
  add column if not exists source_updated_at timestamptz,
  add column if not exists load_batch_id uuid,
  add column if not exists loaded_at timestamptz default clock_timestamp(),
  add column if not exists calculation_as_of_date date;

alter table public.fact_loss
  add column if not exists source_txn_id text,
  add column if not exists source_updated_at timestamptz,
  add column if not exists load_batch_id uuid,
  add column if not exists loaded_at timestamptz default clock_timestamp();

with premium_match as (
  select distinct on (f.premium_key)
    f.premium_key, s.source_txn_id, s.source_updated_at, s.batch_id
  from public.fact_premium f
  join public.dim_policy p on p.policy_key = f.policy_key
  join staging.raw_premium_txn s
    on s.policy_number = p.policy_number
   and to_char(s.txn_date, 'YYYYMMDD')::integer = f.txn_date_key
   and s.written_premium is not distinct from f.written_premium
  order by f.premium_key, s.source_updated_at desc, s.landing_id desc
)
update public.fact_premium f
set source_txn_id = m.source_txn_id,
    source_updated_at = m.source_updated_at,
    load_batch_id = m.batch_id,
    loaded_at = coalesce(f.loaded_at, clock_timestamp()),
    calculation_as_of_date = coalesce(f.calculation_as_of_date, current_date)
from premium_match m
where f.premium_key = m.premium_key;

with claim_match as (
  select distinct on (f.loss_key)
    f.loss_key, s.source_txn_id, s.source_updated_at, s.batch_id
  from public.fact_loss f
  join staging.raw_claim_txn s
    on s.claim_number = f.claim_number
   and to_char(s.txn_date, 'YYYYMMDD')::integer = f.txn_date_key
  order by f.loss_key, s.source_updated_at desc, s.landing_id desc
)
update public.fact_loss f
set source_txn_id = m.source_txn_id,
    source_updated_at = m.source_updated_at,
    load_batch_id = m.batch_id,
    loaded_at = coalesce(f.loaded_at, clock_timestamp())
from claim_match m
where f.loss_key = m.loss_key;

do $$
begin
  if exists (
    select 1 from public.fact_premium
    where source_txn_id is null or source_updated_at is null or load_batch_id is null
       or loaded_at is null or calculation_as_of_date is null
  ) or exists (
    select 1 from public.fact_loss
    where source_txn_id is null or source_updated_at is null or load_batch_id is null
       or loaded_at is null
  ) then
    raise exception 'Warehouse v2 fact-key backfill did not resolve every existing fact';
  end if;

  if exists (
    select source_txn_id from public.fact_premium
    group by source_txn_id having count(*) > 1
  ) or exists (
    select source_txn_id from public.fact_loss
    group by source_txn_id having count(*) > 1
  ) then
    raise exception 'Warehouse v2 fact-key backfill produced duplicate source keys';
  end if;
end
$$;

alter table public.fact_premium
  alter column source_txn_id set not null,
  alter column source_updated_at set not null,
  alter column load_batch_id set not null,
  alter column loaded_at set not null,
  alter column calculation_as_of_date set not null;
alter table public.fact_loss
  alter column source_txn_id set not null,
  alter column source_updated_at set not null,
  alter column load_batch_id set not null,
  alter column loaded_at set not null;

create unique index if not exists fact_premium_source_txn_uidx
  on public.fact_premium (source_txn_id);
create unique index if not exists fact_loss_source_txn_uidx
  on public.fact_loss (source_txn_id);
create index if not exists fact_premium_source_updated_idx
  on public.fact_premium (source_updated_at, source_txn_id);
create index if not exists fact_loss_source_updated_idx
  on public.fact_loss (source_updated_at, source_txn_id);

alter table public.dim_policy
  add column if not exists attribute_hash text,
  add column if not exists source_updated_at timestamptz,
  add column if not exists created_run_id uuid,
  add column if not exists updated_run_id uuid;

update public.dim_policy p
set attribute_hash = coalesce(
      p.attribute_hash,
      md5(concat_ws('|', p.lob_key::text, p.insured_key::text, p.agent_key::text,
        p.effective_date::text, p.expiration_date::text, p.status))
    ),
    source_updated_at = coalesce(
      p.source_updated_at,
      (
        select max(s.source_updated_at)
        from staging.raw_premium_txn s
        where s.policy_number = p.policy_number
      ),
      clock_timestamp()
    );

alter table public.dim_policy
  alter column attribute_hash set not null,
  alter column source_updated_at set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'dim_policy_valid_range_check'
      and conrelid = 'public.dim_policy'::regclass
  ) then
    alter table public.dim_policy
      add constraint dim_policy_valid_range_check
      check (valid_to is null or valid_to > valid_from);
  end if;

  if exists (
    select 1
    from public.dim_policy a
    join public.dim_policy b
      on a.policy_number = b.policy_number
     and a.policy_key < b.policy_key
     and daterange(a.valid_from, coalesce(a.valid_to, 'infinity'::date), '[)') &&
         daterange(b.valid_from, coalesce(b.valid_to, 'infinity'::date), '[)')
  ) then
    raise exception 'Existing policy versions overlap; cannot enable SCD2 exclusion';
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'dim_policy_no_overlapping_versions'
      and conrelid = 'public.dim_policy'::regclass
  ) then
    alter table public.dim_policy
      add constraint dim_policy_no_overlapping_versions
      exclude using gist (
        policy_number with =,
        daterange(valid_from, coalesce(valid_to, 'infinity'::date), '[)') with &&
      );
  end if;
end
$$;

alter table public.dq_results
  add column if not exists pipeline_run_id uuid references public.pipeline_runs(run_id);
create index if not exists dq_results_pipeline_run_idx
  on public.dq_results (pipeline_run_id, checked_at desc);

alter table public.pipeline_runs
  add column if not exists mode text default 'full',
  add column if not exists scenario text,
  add column if not exists watermark_start jsonb,
  add column if not exists watermark_end jsonb,
  add column if not exists source_rows integer,
  add column if not exists inserted_rows integer,
  add column if not exists updated_rows integer,
  add column if not exists unchanged_rows integer,
  add column if not exists recalculated_rows integer,
  add column if not exists rejected_rows integer,
  add column if not exists freshness_lag_seconds integer,
  add column if not exists recovered_from_run_id uuid references public.pipeline_runs(run_id);

insert into ops.etl_watermarks (
  source_name, watermark_ts, watermark_source_id, updated_at
)
select 'premium', source_updated_at, source_txn_id, clock_timestamp()
from staging.raw_premium_txn
order by source_updated_at desc, source_txn_id desc
limit 1
on conflict (source_name) do nothing;

insert into ops.etl_watermarks (
  source_name, watermark_ts, watermark_source_id, updated_at
)
select 'claim', source_updated_at, source_txn_id, clock_timestamp()
from staging.raw_claim_txn
order by source_updated_at desc, source_txn_id desc
limit 1
on conflict (source_name) do nothing;

-- Empty-source fallback keeps composite-watermark comparisons total.
insert into ops.etl_watermarks (source_name, watermark_ts, watermark_source_id)
values
  ('premium', '-infinity'::timestamptz, ''),
  ('claim', '-infinity'::timestamptz, '')
on conflict (source_name) do nothing;

revoke all on all tables in schema public from public, anon, authenticated;
revoke all on all sequences in schema public from public, anon, authenticated;
grant select on
  public.vw_kpi_summary,
  public.vw_loss_ratio_by_lob,
  public.vw_premium_trend_monthly,
  public.vw_loss_trend_monthly,
  public.vw_top_agents,
  public.vw_state_premium,
  public.vw_data_quality_latest,
  public.vw_warehouse_objects,
  public.vw_pipeline_runs
to anon, authenticated, service_role;
